### ISSUE TITLE
.

### ISSUE THREAD

**Issue by yisar** [QingWei-Li/donate#3]
哥你在吗，是这样的，俺写了一个 ssr 框架，然后想用 `skr` 这个 npm 包名
然后发现你是 owner，就想问问能不能 py 交易一波？
俺微信 shibuyayuri，看你也在上海，可以线下面基撒

**Comment by QingWei-Li** [comment]
npm 账号发一下 我转给你 @yisar

**Comment by yisar** [comment]
@QingWei-Li `yse`

**Comment by QingWei-Li** [comment]
已邀请
